### ISSUE TITLE
@sap-ux/backend-proxy-middleware doesn't support multiple paths

### ISSUE THREAD

**Issue by ThePlenkov** [SAP/open-ux-tools#1119]
Hi!

I have reviewed the code and it seems that backend-proxy-middleware doesn't support multiple paths as it's documented:
https://github.com/SAP/open-ux-tools/tree/main/packages/backend-proxy-middleware#changing-the-path-to-which-a-request-is-proxied

So this kind of definition:
```
- name: backend-proxy-middleware
  afterMiddleware: compression
  configuration:
    backend:
    - path: /services/odata
      pathReplace: /my/entry/path
      url: https://my.backend.example:1234
      destination: my_example_destination
```

gives this error:
```
Error Message:
Failed to register backend for undefined. Check configuration in yaml file. 
        Error: Unable to determine target from configuration:
```

Could you please have a look and advise how to design multiple paths for the same destination?

Actually I came here from another place.  VS code extension has migrated my neo-app.json to such a format  and fiori-tools-proxy fails now.

Thanks!

**Comment by tobiasqueck** [comment]
I just reviewed the documentation and the human readable texts are correctly only talking about one path, however, you finding is correct, the sample code snippet is wrong, `backend` is an object and not an array.
To have a proxy for multiple paths, please use two instances of the middleware e.g. 
```yaml
- name: backend-proxy-middleware
  afterMiddleware: compression
  configuration:
    backend:
    - path: /my/path
      pathReplace: /my/entry/path
      url: https://my.backend.example:1234
- name: backend-proxy-middleware
  afterMiddleware: compression
  configuration:
    backend:
    - path: /my/other/path
      url: https://my.backend.example:1234
```
