### ISSUE TITLE
BUG - Incorrect message shown for ABAP deployment when using a URL 

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#1208]
### Related Feature
Feature request: _issue number_

### Description
When using the following ui5-deploy.yaml configuration;

```
  customTasks:
    - name: deploy-to-abap
      afterTask: generateCachebusterInfo
      configuration:
        strictSsl: false
        target:
          url: http://myinternal-host:50000
        app:
          name: ZE2EWRKLTEC1
          description: My Deployed Worklist V2 App
          package: $TMP
          transport: ""
        exclude:
          - /test/
```

A timeout is handled and the following message is outputted;

```
info abap-deploy-task ZE2EWRKLTEC1 ZE2EWRKLTEC1 found on target system: false
warn abap-deploy-task ZE2EWRKLTEC1 Warning: The application was deployed despite a time out response from the backend. Increasing the value of the HTML5.Timeout property for the destination may solve the issue
```

The HTML5.Timeout is not applicable here since there is no reference to any destination.

### Steps to Reproduce
1. Generate a Fiori UI app
2. Deploy the application

### Expected results

Error message does not include the HTML5.Timeout string.

### Actual results

HTML5.Timeout is shown but a destination was not used to deploy.

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}
