### ISSUE TITLE
BUG - generated archive is not excluding test folder

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#1213]
### Description
When generating an archive zip for ABAP deployment, the `exclude` property is being ignored.

Sample config;
```
- name: abap-deploy-task
  configuration:
    app:
      name: Z_TEST
      package: $TMP
    target:
      url: https://target.example
    exclude:
      - /test/
```
Sampe deploy command;

```
./bin/deploy -c jl01021015/ui5-deploy.yaml --verbose true
```

In some ABAP environments this is causing an issue where the deploy command fails with the error;

```
Command deploy failed with error read ETIMEDOUT
```

Removing the test folder and redeploying resolves the issue.

### Steps to Reproduce
1. You have generated a Fiori UI application
2. You run the deploy command
3. Application is successfully deployed

### Expected results

The archive.zip should not contain the test folder.

### Actual results

Archive.zip contains test folder and scripts

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [X] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}
