### ISSUE TITLE
BUG - User credentials are not accepted when a HTTP 401 response is received

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#1396]
### Related Feature
Introduced as part of https://github.com/SAP/open-ux-tools/issues/1330

### Description
User is trying to deploy against an ABAP target system and when prompted for their credentials, a 401 is returned. Reverting to an earlier version of `@sap-ux/deploy-tooling` i.e. v0.10.2 works and the same crendentials are accepted.

Sample ui5.yaml
```yaml
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json

specVersion: "2.6"
metadata:
  name: test.com.ze2effworklistv2abap
type: application
builder:
  resources:
    excludes:
      - /test/**
      - /localService/**
  customTasks:
    - name: abap-deploy-task
      afterTask: generateCachebusterInfo    
      configuration:
        strictSsl: false
        ssl: false
        target:
          url: https://abap-sys.sap:44300
        app:
          name: ZE2EWRKLTEC1
          description: My Deployed Worklist V2 App
          package: $TMP
          transport: ""
        exclude:
          - /test/
 ```

### Steps to Reproduce
1. Generate a Fiori UI app
2. Tweak the ui5.yaml as above, pointing to system that requires basic auth
3. Install the latest version;
```bash
npm install @sap-ux/deploy-tooling --save-dev
```
4. Try to deploy using the command;
```
npx deploy -c ui5-deploy.yaml --no-strict-ssl --verbose
```

### Expected results

Credentials are accepted and deployment is successful.

### Actual results

User is unable to get past the credentials prompt.

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}
