### ISSUE TITLE
BUG -  Generation of sap-fe-mockserver middleware configuration files, does not append annotations to the configuration

### ISSUE THREAD

**Issue by martinjanus-sap** [SAP/open-ux-tools#1735]
### Description

When generating a Fiori Elements application, multiple yaml files are generated. In those yaml files, the sap-fe-mockserver is configured. Unfortunately, in the configuration the annotations are configured with an empty array.

This empty array creates an issue if you run the local karma or do run the azure pipeline. The mockserver does not find the annotations, which results e.g. in a empty table. This effect cannot be seen running OPA5 tests in Business Application Studio. This makes the life from an application developer hard.

### Solution 
Please add the configuration to the annotation.xml when generating according to the following documentation.

https://github.com/SAP/open-ux-odata/tree/main/packages/ui5-middleware-fe-mockserver#usage

### Expected results
Example Correct Entry: 
```
- name: sap-fe-mockserver
  mountPath: /
  beforeMiddleware: csp
  configuration:
    annotations:
      - localPath: './webapp/localService/UI_MANAGEREPAIROBJECTS_VAN.xml'
        urlPath: '/sap/opu/odata/IWFND/CATALOGSERVICE;v=2/Annotations*'
    services:
      - urlPath: '/sap/opu/odata/sap/UI_MANAGEREPAIROBJECTS'
        metadataPath: './webapp/localService/metadata.xml'
        mockdataPath: './webapp/localService/data'
```

### Actual results
```
    - name: sap-fe-mockserver
      beforeMiddleware: csp
      configuration:
        mountPath: /
        services:
          - urlPath: /sap/opu/odata/sap/SEPMRA_PROD_MAN
            metadataPath: ./webapp/localService/metadata.xml
            mockdataPath: ./webapp/localService/data
            generateMockData: true
        annotations: []
```

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [X] Mac OS
- [X] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}
