### ISSUE TITLE
BUG - ODataModel not getting called when adding authorization header 

### ISSUE THREAD

**Issue by matt1as** [SAP/open-ux-tools#2070]
### Description
We have an fiori application where we call a SuccessFactors OData service secured by a JWT Bearer token, but since about two weeks it is not working anymore. 

If we add an authorization header to our ODataModel it receievs a http 401 error when trying to fetch metadata, and i cannot see anything in the terminal output of Business Application Studio. 

If I remove the authorization header I get the expected result, a popup asking for Basic Auth and a log in the BAS Terminal. If I add the header I get a 401 far too quick (20ms) for it to be coming from SuccessFactors, and no log in BAS. 

### Steps to Reproduce
1. Create Odata model and try to read
`  const oDataModel = new ODataModel({
                        "serviceUrl": "/odata/v2",
                        "headers": {
                            "Authorization": "Bearer " + variable_containing_jwt
                        }
                    });`
2. Call GET on the model 
`ODataModel.read('entity')`;
4. Look in Chrome Developer network view
5. See error

### Expected results
call visible in BAS Terminal 
and metadata getting loadeed from /odata/v2

### Actual results
401 received in around 20ms and no call visible in BAS Terminale

#### Version/Components/Environment	
The call os routed using fiori-tools-proxy with the follwing settings.

The JWT works when trying using or REST Client. 

```
specVersion: "2.0"
metadata:
  name: appname
type: application
server:
  customMiddleware:
    - name: fiori-tools-proxy
      afterMiddleware: compression
      configuration:
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
        backend:
          - path: /odata/v2
            destination: successfactors
          - path: /sap/opu/odata
            destination: gateway

    - name: fiori-tools-preview
      afterMiddleware: compression
      configuration:
        component: las.las
        ui5Theme: sap_horizon
```
 I am pretty sure it has worked, and it is still working when running deployed on a ABAP system, which is why I'm thinking it might be related to backend-proxy-middleware. 

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}
