### ISSUE TITLE
BUG - unable to deploy to onpremise destination when webideusage is configured as odata_gen

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#2272]
### Description

When deploying to a SAP BTP destination the following error is thrown;

```
error builder:custom deploy-to-abap Cannot read properties of undefined (reading 'bind')
Command deploy failed with error : Cannot read properties of undefined (reading 'bind')
```

The reason is due to the SAP BTP destination configured with `odata_gen` which causes the following method to return false;

https://github.com/SAP/open-ux-tools/blob/main/packages/axios-extension/src/factory.ts#L209

Sample destination;
```JSON
    {
        "Type": "HTTP",
        "HTML5.DynamicDestination": "true",
        "Authentication": "BasicAuthentication",
        "WebIDEUsage": "odata_gen",
        "Name": "MYTESTDEST",
        "WebIDEEnabled": "true",
        "ProxyType": "OnPremise",
        "WebIDESystem": "SAP",
        "Host": "http://billing.hana.ondemand.com:50001"
    }
```

Sample ui5-deploy;
```yaml
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json

specVersion: "3.1"
metadata:
  name: hansenpoc02
type: application
builder:
  resources:
    excludes:
      - /test/**
      - /localService/**
  customTasks:
    - name: deploy-to-abap
      afterTask: generateCachebusterInfo
      configuration:
        log: 4
        verbose: true
        test: true
        createTransport: true
        target:
          destination: MYTESTDEST
          url: http://billing.hana.ondemand.com:50001       
        app:
          name: ztest
          description: Test
          package: testpackage
          transport: testpackage
        exclude:
          - /test/

```

To unblock the deployment step, change `WebIDEUsage` to `odata_abap`.

### Steps to Reproduce
Steps to reproduce the behaviour:
1. Create a destination with `WebIDEUsage` configured as `odata_gen` 
2. Create any type of project
3. Ensure to add ABAP deployment
4. Run deployment step `npm run deploy`

### Expected results

To deploy correctly

### Actual results

Deployment fails and there is no explanation.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}
