### ISSUE TITLE
BUG - `ext`parameter does not work on fiori-tools-appreload

### ISSUE THREAD

**Issue by marianfoo** [SAP/open-ux-tools#2544]
### Related Feature
Feature request: #1042 

### Description

When i run `fiori-tools-appreload` the property documented `ext` is not applied.

### Steps to Reproduce
1. use `fiori-tools-appreload`
3. add `ext` to yaml
```yml
    - name: fiori-tools-appreload
      afterMiddleware: compression
      configuration:
        debug: true
        port: 35729
        path: webapp
        delay: 300
        ext: "xml,json,properties"
``` 
3. start server
4. see debug output, still default output (which also does not match doc)

```bash
Protocol version: 7
Exclusions: /\.git\//,/\.svn\//,/\.hg\//
Extensions: html,js,ts,json,xml,properties,change,variant,appdescr_variant,ctrl_variant,ctrl_variant_change,ctrl_variant_management_change
Polling: false
```

Documentation

```md
<string> (default: html,js,json,xml,properties,change) Change this parameter to select a custom set of file extensions that are to be watched
```

### Expected results

Only reload on `js` files

### Actual results

Reloads on default extensions

#### Version/Components/Environment	

@sap/ux-ui5-tooling: `1.15.3
`
Add any other context about the problem here
OS:                      
- [ X] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}
