### ISSUE TITLE
BUG - scp deploy configuration parameter not being set correctly

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#2608]
### Related Feature
Found when testing https://github.com/SAP/open-ux-tools/issues/2128

### Description

When running the following command to add deploy configuration;

```bash
yo @sap/fiori:deploy-config --base ui5.yaml --config ui5-deploy.yaml --logLevel debug
```

The SCP prompt state is being reset from `true` to `false` and thus using the incorrect abap service provider to validate the transport and package values.

This is then creating a` ui5-deploy.yaml` deploy configuration with the scp parameter missing;

Generated output;
```
  customTasks:
    - name: deploy-to-abap
      afterTask: generateCachebusterInfo
      configuration:
        target:
          url: https://some.local
          scp: true
```
Expected output;

```
  customTasks:
    - name: deploy-to-abap
      afterTask: generateCachebusterInfo
      configuration:
        target:
          url: https://some.local
          scp: true
```

### Expected results

The existing SAP system should be used to authenticate the user using the service keys;

```
 indexGenerationAllowed false
? Select Target system YTest (BTP) (Source system)
? SAPUI5 ABAP Repository TR
? Deployment Description 
? How do you want to enter the package? Enter manually
⠼ Package tr2024-11-21 13:58:34 info    main: Got authCode 
⠇ Package tr2024-11-21 13:58:34 info    main: Refresh token issued 
2024-11-21 13:58:34 info    main: Got access token successfully 
? Package tr
? How do you want to enter the transport request? Enter manually
? Transport Request (mandatory) TR
```

### Actual results

```
? Select Target system Enter Target System URL
? Target System URL https://someurl.local
? Is this an SAP Business Technology Platform system? No
? Enter client 100
? SAPUI5 ABAP Repository TR
? Deployment Description TR
? How do you want to enter the package? Enter manually
? Package TR
? How do you want to enter the transport request? Enter manually
? Transport Request (mandatory) TR
```

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}
