### ISSUE TITLE
[ui5-proxy-middleware] FEATURE: Allow to specify pathRewrite for resources and testResources paths

### ISSUE THREAD

**Issue by tavnabisoft** [SAP/open-ux-tools#2808]
### Description
It's not possible to map ui5 resources path to custom ones rather than `/resources` and `/test-resources`.  The path taken from `confuguration`->`ui5`-`path` is passed as string instead with no option to pass mapping. This causes problems with overlapping libraries consumed by application/component, that are also exposed under `/resources` path, thus can't be consumed anymore.

What is expected is similar to `pathReplace` option in backend-proxy-middleware:
```yaml
server:
  customMiddleware:
  - name: ui5-proxy-middleware
    afterMiddleware: compression
    configuration:
      ui5:
      - path: /ui5-resources
        pathReplace: /resources
        url: https://ui5.sap.com
```
