### ISSUE TITLE
TBI - Remove ui5-builder-webide-extension for CF deployment

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#3072]
Description (include screenshots)
CF deployment configuration is using the library `@sap/ui5-builder-webide-extension`, which hasn't been updated in 3 years and uses outdated UI5 tooling versions.

In the open ux tools it’s the addCFDeployTask https://github.com/SAP/open-ux-tools/blob/d08273c791086afc63860ffaee33f3c4cbfd4828/packages/ui5-config/src/ui5config.ts#L636 where the outdated build task is added.

Instead of adding the webide task, the task zipper task should have an additional configuration `relativePaths: true`, for example;

```
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json
specVersion: '4.0'
metadata:
    name: recommendationsapp
type: application
resources:
    configuration:
        propertiesFileSourceEncoding: UTF-8
builder:
    resources:
        excludes:
            - '/test/**'
            - '/localService/**'
    customTasks:
        - name: ui5-task-zipper
          afterTask: generateCachebusterInfo
          configuration:
              archiveName: recommendationsapp
              relativePaths: true
              additionalFiles:
                  - xs-app.json
``` 

With that, the ‘@sap/ui5-builder-webide-extension’ dependency could be removed, but the task zipper version would need to be updated to ^3.4.x https://github.com/SAP/open-ux-tools/blob/d08273c791086afc63860ffaee33f3c4cbfd4828/packages/cf-deploy-config-writer/src/constants.ts#L36

Value
Keeps the libs updated and supported with deploy config.

### Tasks
- [ ] Update ui5-config with changes
- [ ] Update cf-writer with changes
- [ ] Update tests
