### ISSUE TITLE
BUG - issue with latest cf-writer module

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#3113]
### Description
A number of issues have been identified when testing the latest version of `cf-deploy-config-writier`.

Issue 1.
When `generateCAPConfig` is called to generate the CAP deployment configuration, the `package.json` is not being updated with the devDependency `@sap/cds-dk`. This is added as part of the `cds add mta` command which generates the `mta.yaml` and also updates the package.json and is required when the `before-all` script is executed;
```
build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm ci
        - npx cds build --production
```

Issue 2. 
If there is more than one HTML5 app in the CAP `apps` folder, when `generateCAPConfig` is executed, it appends the HTML5 apps to the mta.yaml using the following structure;

```
  - name: captestprojectproject2
    type: html5
    path: app/project2
    build-parameters:
      build-result: dist
      builder: custom
      commands:
        - npm ci
        - npm run build
      supported-platforms:
        []
```
This module type uses a different naming convention i.e.  `captestprojectproject2` instead of `project2` and the command `npm run build` is not supported for SAP Fiori generated apps. To support SAP Fiori generated apps in the mta.yaml, the command needs to be changed to ` npm run build:cf`.

Issue 3.
In some instances, when consuming `generateCAPConfig` or `generateAppConfig` you might want to delay the `npm install` step being executed. For example, you might want to append additional `scripts` to the or append new dependencies or devDependencies to the `package.json`. To support, this these methods need to allow a flag to skip the install phase.

Delaying the install step is important, as the mta.yaml contains a before-all script `npm ci` which will fail since the package.json and package-lock.json are not in sync.  In the case of the SAP Fiori tools generator, the install lifecycle method, will instead invoke the required `npm install` step which will align the required files to support `npm ci`.

### Steps to Reproduce
Sample code;
```
const fs1 = await generateCAPConfig({ mtaId: 'mymtaproject', routerType: RouterModuleType.Managed, mtaPath }, null, logger);
const ui5AppPath = join(__dirname, '../../captestproject/app/project1');
const fs2 = await generateAppConfig({appPath: ui5AppPath, addManagedAppRouter: true, destinationName: 'fiori-default-srv-api'}); 
  return new Promise((resolve) => {
     fs1.commit(resolve);
     fs2.commit(resolve);
  });
}
```
Since the `install` step is executed per step, the command `npm ci` fails as the package.json and package-lock.json are not in sync.

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}
