### ISSUE TITLE
TBI - suppprt CDS generated mta configurations with SAP Fiori tools generated HTML5 apps

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#3290]
### Description (include screenshots)
Currently, SAP Fiori tools requires HTML5 projects to expose a `package.json` script called `build:cf`, for example

https://github.com/SAP-samples/fiori-tools-samples/blob/main/cap/cap-fiori-mta/app/feproject-ui/package.json#L13

```json
    "scripts": {
        "deploy-config": "npx -p @sap/ux-ui5-tooling fiori add deploy-config cf",
        "build:cf": "ui5 build preload --clean-dest --config ui5-deploy.yaml --include-task=generateCachebusterInfo"
    },
```

When running the documented steps below, CDS will generate an mta configuration using `npm run build` as the npm command which is not aligned with the SAP Fiori tools `build:cf` script.

Step1. Generate CAP project
```bash
cds init managedAppCAPProject && cd  managedAppCAPProject && npm install && cds add tiny-sample && cds add hana
```

Step2. Load SAP Fiori tools and append a HTML5 application to the CAP project

Step3. Add mta configuration
```bash
cds add mta && cds add xsuaa && cds add connectivity && cds add destination && cds add html5-repo
```

The generated `mta.yaml` contains the following node;

```yaml
- name: captutorialfeprojectui
  type: html5
  path: app/feproject-ui
  build-parameters:
    build-result: dist
    builder: custom
    commands:
    - npm install
    - npm run build:cf
    supported-platforms: []
```
Example project;
https://github.com/SAP-samples/fiori-tools-samples/blob/main/cap/cap-fiori-mta/mta.yaml

Two changes to align with the CDS flow;
Change 1. 
The CF writer should be updated to append `build` instead of `build:cf` in the HTML5 `package.json`.
Change 2.
The `mta.yaml` configuration generated when using the cf-writer should be aligned with the CDS flow, `npm run build` should be appended instead of `npm run build:cf`. 

### Value
Better alignment with CDS.

### Architecture Elaboration
No.

### Notes
There should be no other changes required, these changes are only required for HTML5 apps inside a CAP project.

### Tasks
- [ ] Update CF writer to apply the recommended changes above
- [ ] Update test cases
