### ISSUE TITLE
TBI - CF writer should align with srv-api destination instance

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#3409]
### Description (include screenshots)
When the following CAP command is run, it generates a `srv-api` instance that should be reused when a HTML5 application is added to an existing mta.yaml configuration;

```bash
cds init managedAppCAPJLProject && cd  managedAppCAPJLProject && npm install && cds add tiny-sample && cds add hana && cds add mta && cds add xsuaa && cds add connectivity && cds add destination && cds add html5-repo && cds build --for hana && cp gen/db/package.json db && npm i
```

`mta.yaml` configuration is updated with a `srv-api` destination instance;

```yaml
          - Authentication: NoAuthentication
            HTML5.DynamicDestination: true
            HTML5.ForwardAuthToken: true
            Name: srv-api
            ProxyType: Internet
            Type: HTTP
            URL: ~{srv-api/srv-url}
```

### Value
Leverage settings appended by CDS.

### Architecture Elaboration
None.

### Tasks
- [ ] Update readme if applicable
- [ ] Udate test cases
- [ ] Re-use `srv-api` is appended by CDS instead of adding a new one
-
