### ISSUE TITLE
BUG - backend-proxy-middleware can't read API Hub Key from the secure store

### ISSUE THREAD

**Issue by zdravko-georgiev** [SAP/open-ux-tools#544]
### Description
Trying to preview an application that uses an OData service from the SAP API Business Hub fails with 401 Error. 

### Steps to Reproduce
1. Generate a List Report application by using the SAP API Business Hub
2. Select as OData service, e.g. `Activity Type - Read (A2X)`
3. After generation install the `backend-proxy-middleware` by executing `npm i @sap-ux/backend-proxy-middleware`.
4. Add the `@sap-ux/backend-proxy-middleware` to the ui5 dependencies in the `package.json`.
5. Remove the `backend` configuration in the `fiori-tools-proxy`.
6. Add the `backend-proxy-middleware` to the `ui5.yaml` like this

```
  - name: backend-proxy-middleware
    afterMiddleware: compression
    configuration:
      backend:
        path: /s4hanacloud
        url: https://sandbox.api.sap.com
        apiHub: true

```
7. Execute `npm start`.

### Expected results
Data is loaded in the application

### Actual results
Data is not loaded in the application

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [x] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}
