### ISSUE TITLE
fiori-tools-proxy disables npm module shims in its' default config

### ISSUE THREAD

**Issue by vobu** [SAP/open-ux-tools#79]
### Description
The issue was initially reported at https://answers.sap.com/questions/13461279/ui5-project-shims-not-working.html?childToView=13479438.
 
When a service is added using the `odata-service` template. the `fiori-tools-proxy` middleware is added to the `ui5.yaml`
```
server:
  customMiddleware:
  - name: fiori-tools-proxy
    afterMiddleware: compression
    configuration:
# ...
      ui5:
        path:
        - /resources # <-- this line makes the proxy intercept everything with the prefix /resources
        - /test-resources
        url: https://ui5.sap.com
        version:  # The UI5 version, for instance, 1.78.1. Empty means latest version
```
If a developer then wants to using the shimming functionality and adds a configuration like
```
specVersion: '2.1'
kind: extension
type: project-shim
metadata:
  name: thirdparty # this can be your project shim name
shims:
  configurations:
    lodash: # name as defined in package.json
      specVersion: '2.1'
      type: module # Use module type
      metadata:
        name: lodash
      resources:
        configuration:
          paths:
            /resources/thirdparty/lodash/: ''  # never getting here because the proxy intercepts it before
```
It doesn't work because the shimming capability requires `resources` not to be generically proxied, as it relies on a subdir of `resources` to make the npm module available at runtime.
 
### Steps to Reproduce
1. Run the tests in the `fiori-freestyle` template
2. Enhance the one of the generated projects in the `test-output` folders with the shim configuration above
3. Try reaching any file in `/resources/thirdparty/lodash`
4. See 404 not found error
 
 
### Expected results
Actual file is returned.
 
 
### Actual results
404
 
 
### Screenshots
-n/a-
 
 
#### Version/Components/Environment              
Add any other context about the problem here
OS:                     
- [x] Mac OS
- [x] Windows
- [x] Other
 
### Problem
See description
 
### Fix
Different options
 
1. Change the generated `ui5.yaml` to only proxy requests start with sap
```
ui5:
  path:
    - /resources/sap*
```
2. Leave the template as-is and report the issue to the `fiori-tools-proxy` team
3. Leave it as is and document that users that require shimming have to change the default settings
 
### Why was it missed
This feature is not covered in a test case. 
 
### How can we avoid this
Create a test case covering it.

pinging @petermuessig @tobiasqueck as FYI

**Comment by tobiasqueck** [comment]
@Klaus-Keller what do you think? Is this something that should be fixed in the `fiori-tools-proxy` or should we update the templates as @vobu suggested as fix option 1?

@petermuessig is there anything not starting with `sap` at `https://ui5.sap.com` that we could/would/might need during the preview?

**Comment by Klaus-Keller** [comment]
@petermuessig, for custom middleware we have a defined execution order and can also influence this execution order, for instance using
 
```
afterMiddleware: compression
```

Does such an option also exist for project shims? Couldn't find a way to influence execution order in https://sap.github.io/ui5-tooling/pages/extensibility/ProjectShims/

**Comment by tobiasqueck** [comment]
@RandomByte could you help us here?

**Comment by zdravko-georgiev** [comment]
Hi @RandomByte, it is a good idea, but unfortunately it doesn't work as expected. It is due to the fact that the [http-proxy-middleware](https://www.npmjs.com/package/http-proxy-middleware) (the middleware that we are using in the `fiori-tools-proxy`) doesn't really support this feature (please see [Issue248](https://github.com/chimurai/http-proxy-middleware/issues/248) for reference).

I can call `next()`, but then I get an exception `Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`, because `res.end()` was called as soon as 404 was received.

**Comment by petermuessig** [comment]
Hi all, and sorry for joining the party that late. Basically, the UI5 resources of today are typically in the `resources/sap*` location but there are some special cases for the jQuery plugins, the `ui5loader.js` or `ui5loader-autoconfig.js`. 

I like the suggestion of Merlin but this would mean the proxy middleware would require a response stub which is used to intercept the calls like setting the headers and res.end() - I did this in Java for some Servlets in the past and this may also work for NodeJS. Maybe just put a `Proxy` around and intercept the required functions like `setHeader` or `end`.

Cheers, Peter

**Comment by zdravko-georgiev** [comment]
### Update
We decided to go for the idea where the `fiori-tools-proxy` calls the next available middleware (`next()`), if the proxy target returns 404. The fix is currently being implemented. Afterwards it will undergo quality assurance. If it all goes well we should have it released in 3-4 weeks.

**Comment by zdravko-georgiev** [comment]
## Update
The fix didn't make it in the next release. Now it should be released mid of January.

**Comment by zdravko-georgiev** [comment]
### Update
Fix was submitted to the main branch. The fix will now undergo quality assurance and if all goes well it will be released at the end of this month.

**Comment by zdravko-georgiev** [comment]
Fixed with https://www.npmjs.com/package/@sap/ux-ui5-tooling/v/1.4.7.

**Comment by zdravko-georgiev** [comment]
Hello,
we needed to revert the fix, because the fix was not stable. There were multiple reports of the error 
```Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client```. 
At this point in time we will not provide a fix for this. Please refer to https://answers.sap.com/questions/13461279/ui5-project-shims-not-working.html?childToView=13479438 for the workaround.

Best regards,
Zdravko

**Comment by vobu** [comment]
well, the workaround in https://answers.sap.com/questions/13461279/ui5-project-shims-not-working.html?childToView=13479438 is not really a workaround as a pattern like 
```yaml
ui5:
        path: 
        - /resources/sap*
```
will **not** proxy `ui5-loader*` or any `jquery*` resources.

**Comment by tobiasqueck** [comment]
The sources responsible have been published by now and are at https://github.com/SAP/open-ux-tools/tree/main/packages/ui5-proxy-middleware. 
@vobu any proposal how to fix it? Should we open the issue?

Btw, wouldn't the config below solve the issue?
```yaml
ui5:
        path: 
        - /resources/sap*
        - /resources/ui5-loader*
        - /resources/jquery*
```

**Comment by proehlen** [comment]
> Hello, we needed to revert the fix, because the fix was not stable. 

Hi just enquiring if a fix is still being considered for this or if the issue has been moved to a new discussion?

**Comment by zdravko-georgiev** [comment]
Hi @proehlen, currently we are not considering to provide a fix for this issue.

**Comment by Kyrodan** [comment]
In https://github.com/ui5-community/ui5-ecosystem-showcase/issues/1149 I have a similar problem.
The mentioned Workaround https://github.com/SAP/open-ux-tools/issues/79#issuecomment-1091870937 does not work (anymore?) for me.
Any suggestions?

**Comment by tobiasqueck** [comment]
> In [ui5-community/ui5-ecosystem-showcase#1149](https://github.com/ui5-community/ui5-ecosystem-showcase/issues/1149) I have a similar problem. The mentioned Workaround [#79 (comment)](https://github.com/SAP/open-ux-tools/issues/79#issuecomment-1091870937) does not work (anymore?) for me. Any suggestions?

Could you share your `ui5.yaml` please?

**Comment by Kyrodan** [comment]
HI @tobiasqueck 

> Could you share your `ui5.yaml` please?
My ui5.yaml looks like:
```
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json
specVersion: '4.0'
metadata:
  name: my.app
customConfiguration:
  config-ui5-tooling-transpile: &cfgTranspile
    debug: true
    transformModulesToUI5:
      overridesToOverride: true
    transformAtStartup: false
    transpileDependencies: true
    filePattern: .+(js|ts)
    excludes:
      - /Component-preload.js
      - /lib/
type: application
server:
  customMiddleware:
    - name: fiori-tools-proxy
      afterMiddleware: compression
      configuration:
        ignoreCertError: false # If set to true, certificate errors will be ignored. E.g. self-signed certificates will be accepted
        backend:
          - path: /sap
            url: http://mysapserver.local:8000
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
    - name: ui5-tooling-transpile-middleware
      afterMiddleware: compression
      configuration:
        <<: *cfgTranspile
    - name: fiori-tools-appreload
      afterMiddleware: compression
      configuration:
        port: 35729
        path: webapp
        delay: 300
    - name: fiori-tools-preview
      afterMiddleware: fiori-tools-appreload
      configuration:
        component: my.app
        ui5Theme: sap_horizon
```

What I'm trying to achive:
use ui5-tooling with library dependencies in package.json and a ui5-workspace.yaml. All dependencies get resolved by ui5-tooling but if I use fiori-tools-proxy the library dependency does not get served anymore (the mount to "/resources" breaks this expected behavior.
I changed the ui5.yaml resources-path like this:
* /resources/sap/ => works for all subpathes of ui5-Lib and my resolved library  dependencies
* /resources/sap* => does not work at all, ui5-library cannot be resolved anymore
Also tried using ui5-middleware-simpleproxy with excludePatterns (instead of fiori-tools-proxy middleware) => serving ui5-lib works and exclude works as expected. But I cannot mount several paths and doesn't have the full power of ui5-lib-determination.

**Comment by tobiasqueck** [comment]
@Kyrodan it seems the `*` doesn't work. Please use
```yaml
      configuration:
        ui5:
          path:
          - /resources/sap
          - /resources/sap-ui-core.js
          - /test-resources
```
If you need additional root files or root folders, just add them to the list.
